/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Registro;

import java.util.ArrayList;
import ManejoArchivo.ArchivoRegistro;
import ManejoArchivo.ArchivoBinario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author INSTEBEHO
 */
public class Registro extends javax.swing.JFrame {

    ArrayList<Paciente> listaPaciente;

    Paciente paciente;

    public Registro() {
        listaPaciente = new ArrayList<>();
        initComponents();
        
        
        listaPaciente=  ArchivoBinario.leerArchivo();
        if(listaPaciente!=null)
            pintarTabla();
        else
            listaPaciente= new ArrayList<>();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PacienteTabla = new javax.swing.JTable();
        identificaciontxt = new javax.swing.JTextField();
        nombretxt = new javax.swing.JTextField();
        tipocombox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        generocombox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jCalender = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripciontxt = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(23, 79, 103, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tipo de Sangre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 220, 103, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Fecha de Nacimiento");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 30, 140, 30);

        PacienteTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(PacienteTabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 360, 640, 110);

        identificaciontxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        identificaciontxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificaciontxtActionPerformed(evt);
            }
        });
        getContentPane().add(identificaciontxt);
        identificaciontxt.setBounds(120, 30, 200, 40);

        nombretxt.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        nombretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombretxtActionPerformed(evt);
            }
        });
        getContentPane().add(nombretxt);
        nombretxt.setBounds(120, 80, 200, 40);

        tipocombox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tipocombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        getContentPane().add(tipocombox);
        tipocombox.setBounds(130, 220, 150, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(660, 310, 120, 23);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(660, 280, 120, 23);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Salir");
        getContentPane().add(jButton3);
        jButton3.setBounds(670, 460, 120, 23);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Modificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(660, 340, 120, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Descripción ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(380, 120, 103, 30);

        generocombox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        generocombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Femenino", "Masculino" }));
        getContentPane().add(generocombox);
        generocombox.setBounds(130, 160, 150, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Identificacion");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(23, 31, 103, 30);
        getContentPane().add(jCalender);
        jCalender.setBounds(490, 30, 200, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Genero");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 150, 103, 30);

        descripciontxt.setColumns(20);
        descripciontxt.setRows(5);
        jScrollPane2.setViewportView(descripciontxt);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(490, 80, 200, 110);

        jMenu1.setBorder(new javax.swing.border.MatteBorder(null));
        jMenu1.setText("Ver");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Historial Clinico");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(815, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void identificaciontxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificaciontxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificaciontxtActionPerformed

    private void nombretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombretxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombretxtActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        agregar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (listaPaciente.size() <= 0) {
            JOptionPane.showMessageDialog(rootPane, "La listá está vacía y no hay nada para guardar");
        } else {
            ArchivoBinario.escribirArchivo(listaPaciente);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void limpiar() {
        nombretxt.setText("");
        descripciontxt.setText("");
        tipocombox.setSelectedItem("Seleccione");
        generocombox.setSelectedItem("Seleccione");
        identificaciontxt.setText("");
        identificaciontxt.requestFocus();
        

    }

    private void guardarPaciente() {
        Paciente paciente = new Paciente();
        paciente.setIdentificacion(Integer.parseInt(identificaciontxt.getText().trim()));
        paciente.setNombre(nombretxt.getText().trim());
        paciente.setGenero(generocombox.getSelectedItem().toString());
        paciente.setTiposangre(tipocombox.getSelectedItem().toString());
        paciente.setDescripcion(descripciontxt.getText().trim());

        String mensaje = ArchivoRegistro.gueardarPacieente(paciente);
        JOptionPane.showMessageDialog(rootPane, mensaje);

    }

    private void agregar() {
        String nombre, descripcion, genero, tiposabre, identificaciontexto, calendario;
        int identicicacion;

        nombre = nombretxt.getText().trim();
        descripcion = descripciontxt.getText().trim();
        genero = generocombox.getSelectedItem().toString();
        tiposabre = tipocombox.getSelectedItem().toString();
        calendario = jCalender.getDateFormatString();
        identificaciontexto = identificaciontxt.getText().trim();
        identicicacion = Integer.parseInt(identificaciontexto);

        paciente = new Paciente();
        paciente.setIdentificacion(identicicacion);
        paciente.setNombre(nombre);
        paciente.setGenero(genero);
        paciente.setCalendario(calendario);
        paciente.setTiposangre(tiposabre);
        paciente.setDescripcion(descripcion);

        listaPaciente.add(paciente);
        limpiar();
        pintarTabla();

    }

    private void pintarTabla() {
        String[] columnas = {"IDENTIFICACION", "NOMBRE", "GENERO", "TIPO DE SANDRE", "DESCRIPCION DE PACIENTE"};
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(columnas);

        for (Paciente pac : listaPaciente) {
            String[] fila = {String.valueOf(pac.getIdentificacion()), pac.getNombre(), pac.getGenero(), pac.getTiposangre(), pac.getDescripcion()};
            modelo.addRow(fila);
        }

        PacienteTabla.setModel(modelo);
    }

     public  ArrayList<Paciente> getList(){
        return listaPaciente;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PacienteTabla;
    private javax.swing.JTextArea descripciontxt;
    private javax.swing.JComboBox<String> generocombox;
    private javax.swing.JTextField identificaciontxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jCalender;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombretxt;
    private javax.swing.JComboBox<String> tipocombox;
    // End of variables declaration//GEN-END:variables
}
